In [15]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv('dataset/KDDTest+.txt')
df.head()

,0,tcp,private,REJ,0.1,0.2,0.3,0.4,0.5,0.6,...,0.04.1,0.06.1,0.00.3,0.00.4,0.00.5,0.00.6,1.00.2,1.00.3,neptune,21
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal,21
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint,15
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11
4,0,tcp,http,SF,267,14515,0,0,0,0,...,1.00,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal,21

In [17]:
df.columns.tolist()

['0',
 'tcp',
 'private',
 'REJ',
 '0.1',
 '0.2',
 '0.3',
 '0.4',
 '0.5',
 '0.6',
 '0.7',
 '0.8',
 '0.9',
 '0.10',
 '0.11',
 '0.12',
 '0.13',
 '0.14',
 '0.15',
 '0.16',
 '0.17',
 '0.18',
 '229',
 '10',
 '0.00',
 '0.00.1',
 '1.00',
 '1.00.1',
 '0.04',
 '0.06',
 '0.00.2',
 '255',
 '10.1',
 '0.04.1',
 '0.06.1',
 '0.00.3',
 '0.00.4',
 '0.00.5',
 '0.00.6',
 '1.00.2',
 '1.00.3',
 'neptune',
 '21']

In [18]:
df = pd.read_csv("dataset/KDDTrain+.txt")
df.columns.tolist()

['0',
 'tcp',
 'ftp_data',
 'SF',
 '491',
 '0.1',
 '0.2',
 '0.3',
 '0.4',
 '0.5',
 '0.6',
 '0.7',
 '0.8',
 '0.9',
 '0.10',
 '0.11',
 '0.12',
 '0.13',
 '0.14',
 '0.15',
 '0.16',
 '0.18',
 '2',
 '2.1',
 '0.00',
 '0.00.1',
 '0.00.2',
 '0.00.3',
 '1.00',
 '0.00.4',
 '0.00.5',
 '150',
 '25',
 '0.17',
 '0.03',
 '0.17.1',
 '0.00.6',
 '0.00.7',
 '0.00.8',
 '0.05',
 '0.00.9',
 'normal',
 '20']

####

In [19]:
columns = [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
    "label",
    "difficulty"
]

print("Number of columns:", len(columns))

Number of columns: 43

## Loading the train and test data

In [20]:
train_raw = pd.read_csv("dataset/KDDTrain+.txt",header=None, names=columns)
test_raw = pd.read_csv("dataset/KDDTest+.txt",header=None, names=columns)

print("Train shape:", train_raw.shape)
print("Test shape:", test_raw.shape)

train_raw.head()

Train shape: (125973, 43)
Test shape: (22544, 43)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [21]:
##finding the attack label labels and their counts in the training dataset
## Later NORMAL ---> Normal and all other attacks will be labeled as Attack
train_raw["label"].value_counts()

label
normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: count, dtype: int64

In [22]:
def clean(df):
    df = df.drop(columns=["difficulty"])
    df = df.drop_duplicates()
    df = df.replace([np.inf, -np.inf], np.nan).dropna()
    df["binary_label"] = df["label"].apply(lambda x: 0 if x == "normal" else 1)
    return df
train_df = clean(train_raw)
test_df = clean(test_raw)

print("Train after cleaning:", train_df.shape)
print("\nTraining labels:")
print(train_df["binary_label"].value_counts())

print("\nTest labels:")
print(test_df["binary_label"].value_counts())

Train after cleaning: (125973, 43)

Training labels:
binary_label
0    67343
1    58630
Name: count, dtype: int64

Test labels:
binary_label
1    12833
0     9711
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [24]:
cat_cols = ["protocol_type", "service", "flag"]

for col in cat_cols:
    le = LabelEncoder()
    le.fit(pd.concat([train_df[col], test_df[col]]).astype(str))
    train_df[col] = le.transform(train_df[col].astype(str))
    test_df[col] = le.transform(test_df[col].astype(str))

feature_cols = [c for c in train_df.columns if c not in ("label", "binary_label")]

scaler = MinMaxScaler()
train_df[feature_cols] = scaler.fit_transform(train_df[feature_cols])
test_df[feature_cols] = scaler.transform(test_df[feature_cols])

print("Feature columns:", len(feature_cols))
train_df.head()

Feature columns: 41

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,binary_label
0,0.0,0.5,0.289855,0.9,3.558064e-07,0.000000e+00,0.0,0.0,0.0,0.0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,0
1,0.0,1.0,0.637681,0.9,1.057999e-07,0.000000e+00,0.0,0.0,0.0,0.0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,0
2,0.0,0.5,0.710145,0.5,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,1
3,0.0,0.5,0.347826,0.9,1.681203e-07,6.223962e-06,0.0,0.0,0.0,0.0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,0
4,0.0,0.5,0.347826,0.9,1.442067e-07,3.206260e-07,0.0,0.0,0.0,0.0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,0

In [25]:
import joblib
import os

os.makedirs("preprocessing", exist_ok=True)

joblib.dump(scaler, "preprocessing/minmax_scaler.pkl")

print("Scaler saved successfully.")

Scaler saved successfully.

In [26]:
os.makedirs("preprocessing", exist_ok=True)

encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    le.fit(pd.concat([train_df[col], test_df[col]]).astype(str))

    train_df[col] = le.transform(train_df[col].astype(str))
    test_df[col] = le.transform(test_df[col].astype(str))

    encoders[col] = le

joblib.dump(encoders, "preprocessing/label_encoders.pkl")

print("Label encoders saved successfully.")

Label encoders saved successfully.

In [27]:
print("Number of features:", len(feature_cols))
print(feature_cols)

Number of features: 41
['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate']

In [28]:
train_df.to_csv("dataset/train_processed.csv", index=False)
test_df.to_csv("dataset/test_processed.csv", index=False)
print("Saved train_processed.csv and test_processed.csv to dataset/")

Saved train_processed.csv and test_processed.csv to dataset/